# Generated by Django 5.1.4 on 2025-01-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='penalty_team1',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='penalty_team2',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
