# Generated by Django 5.1.4 on 2025-01-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_alter_match_penalty_team1_alter_match_penalty_team2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='penalty_team1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='penalty_team2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
