# Generated by Django 5.1.4 on 2025-01-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_alter_match_penalty_team1_alter_match_penalty_team2'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='penalty_score_team1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='penalty_score_team2',
            field=models.IntegerField(default=0),
        ),
    ]
