# Generated by Django 5.1.4 on 2025-01-06 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_match_penalty_score_team1_match_penalty_score_team2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='penalty_score_team1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='penalty_score_team2',
        ),
    ]
