# Generated by Django 5.1.4 on 2025-01-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_remove_match_penalty_score_team1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.CharField(choices=[('Group Stage', 'Group Stage'), ('Quarterfinals', 'Quarterfinals'), ('Semifinals', 'Semifinals'), ('Final', 'Final')], default='Group Stage', max_length=20),
        ),
    ]
