# Generated by Django 5.1.5 on 2025-01-23 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='bypass_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bypass_winner', to='tournaments.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='is_bypass',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='tournaments.team'),
        ),
    ]
