# Generated by Django 5.1.5 on 2025-02-02 11:16

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_match_bypass_winner_match_is_bypass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='teams_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True),
        ),
    ]
