# Generated by Django 5.1.5 on 2025-02-03 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_team_teams_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='teams_slug',
            new_name='team_slug',
        ),
    ]
